### PR TITLE
Added support for more country maps

### PR DESCRIPTION
**Pull request by clementchong**
This is to address https://github.com/running-elephant/datart/issues/1119

Please help review and approve PR if ok to proceed. Thank you.

### CODE REVIEW

**Comment by xieliuduo** [comment]
There may be a lot of people who need to display the world map data, and we will provide some ways to do that, maybe we won't put the GEO files in the main repository

But don't worry, We can discuss specific plans here #1263 

We appreciate your pr.

**Comment by xieliuduo** [comment]
The following articles may help you develop custom charts

https://mp.weixin.qq.com/s/a4DVf-5LHVQAknmKKE6DJA

https://mp.weixin.qq.com/s/nYMAaiT97NPkm71FpW8LSw

https://mp.weixin.qq.com/s/9hBNSla86Fzouy0WdXqSQQ

This plugin repository might give you some hints ：https://github.com/running-elephant/datart-extension-charts

**Comment by clementchong** [comment]
No worries, I would use this for my local until we have a proper solution

**Comment by scottsut** [comment]
Thanks for the contribution! But we are cautious about importing resource files directly in source code. Everyone who uses datart has different needs for map resource files, we do not plan to provide all map resources in source code, so I will close this PR.

**Comment by clementchong** [comment]
Ok noted. Thank you.

**Pull request closed without merging**
