### PR TITLE
feat: Added simple sql view module

### PR DESCRIPTION
**Pull request by lyp000119**
feat: Added simple sql view module

### CODE REVIEW

**Comment by clementchong** [comment]
Hello, I am not a reviewer. Would you consider adding i18n language support for english for those hardcoded chinese parts?

**Comment by lyp000119** [comment]
> Hello, I am not a reviewer. Would you consider adding i18n language support for english for those hardcoded chinese parts?

Yes, I will

**Comment by scottsut** [comment]
> Hello, I am not a reviewer. Would you consider adding i18n language support for english for those hardcoded chinese parts?

Thanks for your attention! But this is a preview commit 😂, maybe close soon.

**Comment by clementchong** [comment]
Thank you!!

**Pull request closed without merging**
